server {
	listen					443 ssl;
	server_name				malde-ch.42.fr;

	root					/var/www/html;
	index					index.php index.html;

	ssl_certificate			/etc/nginx/ssl/nginx.crt;
	ssl_certificate_key		/etc/nginx/ssl/nginx.key;
	ssl_protocols			TLSv1.2 TLSv1.3;


	    location / {
        try_files $uri $uri/ =404;
    }

	location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
    }

    location /adminer {   
        fastcgi_pass adminer:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    }

	location /website/ {
        proxy_pass http://website:3000/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

	location /cadvisor/ {
        proxy_pass http://cadvisor:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}