listen=YES
listen_ipv6=NO
background=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_address=34.175.82.80
pasv_min_port=21100
pasv_max_port=21110

xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log

local_umask=002

seccomp_sandbox=NO